addons:
  apt:
    update: true
sudo: required
language: python
python:
- '3.5'
script:
- set -e
- pytest
- sudo apt install --yes snapd
- sudo snap install microk8s --classic
- export PATH=/snap/bin:$PATH
- microk8s.status --wait-ready
- snap alias microk8s.kubectl kubectl
- kubectl get pods --all-namespaces
- make image
- make push-image
- make integration-test
env:
  global:
    secure: ryvPKHz+1ph95Wj0hstSSlDiSnqoROs9oa554NszIrqiaQIRlIykwuOPkyicZqzB0airO6ygOp3Ca1MFp4DwoIBZsD/nYeU2oYUBzVHl+MVzdkOxGmSmV/5mO53T2WWCQ7jnRgkLcuJX7Q+pFnmr0cvOK6RodtqugISw9GZSc2aqZ23DA29ft71v8gqoXNjiBf/apl4ymlp6M1DYykgYNvjO3B/5VOxa5YQQ76GbSTRVRyzyH/lIUAIcGAZTvsMNesjQaTC+6vcYtYp7Q9JgP2ZRIAtlZpXiWvYNbroqesNEeQ6GcGb/XgTnsrARny1moYbaAsYQGiNQNRTI9rB5bLwvhmZ3O3/4y/jmJhqorkSpETUDXc2zm+Wjb2jJrl9CjVvjqQQdjC6QWYveLC4nRThWKMx1NAjx/gmAKBbQSronfMqqg4PQEpAjYlP3tRscM57yqS7BauUfCf/jWIdQGsClN1Zb/CVWcqcGNU6/qM4PWEv9HAjyB3kMcs0L+LR7NtGAtPpAI6GOn5B1PHNQCGyOCOnGs37LZySfg30OIpzPHHqFQ6ETjGYhq+IyXtM0WtaSBEA/owlDz17s3HlLmA+bwg1T4AfOjEuDrj7HFF7H4x1EdSec1qREnSoTGYNPyUuhdQ0+5X5li1S0LASOE1RB+Q+Iymu46cvFGBkMUgU=
